### ISSUE TITLE
xpenology video igpu 

### ISSUE THREAD

**Issue by damienmillet** [jim3ma/synology-igc#12]

**Comment by jim3ma** [comment]
Hello, what do you want to talk about ? igpu driver is different with igc driver.

**Comment by damienmillet** [comment]
Hi, i just need igpu but i don't know how backport a driver, maybe can u explain to me or help :3

**Comment by jim3ma** [comment]
The igpu driver code base is very large, I did not recommend to backport it.

**Comment by damienmillet** [comment]
Ok, ty for advise, i ll use a pcie compatible. Can we passthru a gpu to vmm without gui ?

**Comment by jim3ma** [comment]
You can use `virsh` command to manager VMs in VMM for more options like pcie passthrough.

**Comment by damienmillet** [comment]
ok I ll take a look ty
