### ISSUE TITLE
When I used this driver to copy files through SMB services, I experienced a memory overflow and the system crashed

### ISSUE THREAD

**Issue by Aivenpeng** [jim3ma/synology-igc#2]
State
![image](https://user-images.githubusercontent.com/38059391/198812640-c3443188-f716-407d-9132-45cb48bdf2b5.png)
log
![IMG_3475(20221029-115127)](https://user-images.githubusercontent.com/38059391/198812662-1c3ae9a2-0816-4e42-9e37-8a36209e4f4c.PNG)

**Comment by jim3ma** [comment]
I have tested in my DX4600, all is okay.
Does you use it in virtual machine ? Try it in bare metal.

**Comment by Aivenpeng** [comment]
In my tests, I booted on a USB flash drive, not a virtual machine

**Comment by jim3ma** [comment]
Can you provide the `dmesg` log, machine type, cpu&memory and so on?

**Comment by Aivenpeng** [comment]
I used DSM7.0.1. I want to know which version you are using

**Comment by Aivenpeng** [comment]
> 

No problem. I'll test it later and collect some logs for you

**Comment by Aivenpeng** [comment]
Device type：mini pc
CPU model：Intel j4125
Memory size：8G DDR4 2666MHz

**Comment by Aivenpeng** [comment]
[debug.txt](https://github.com/jim3ma/synology-igc/files/9893839/debug.txt)
this is debug logs

**Comment by jim3ma** [comment]
I use dsm 7.1.1.
Please confirm your igc version by `modinfo igc`, I have updated to 1.2.0.

**Comment by Aivenpeng** [comment]
![image](https://user-images.githubusercontent.com/38059391/198848224-0a1cc20a-b55f-4ce5-8cb3-9dfaad6b9b73.png)
igc version

**Comment by Aivenpeng** [comment]
I have checked the igc version. it's the latest 1.2.0.
I tested DSM7.1.1 myself. The same problem arises.
![image](https://user-images.githubusercontent.com/38059391/198871801-48e6cbc2-4328-4888-8199-9618eb1b7c93.png)

**Comment by Aivenpeng** [comment]
I'm going to test it with a virtual machine

**Comment by Aivenpeng** [comment]
@jim3ma 
![image](https://user-images.githubusercontent.com/38059391/198879814-7db550e2-69f6-458e-8a35-9f403aa561e4.png)
This is  screenshot of the version

**Comment by Aivenpeng** [comment]
Using virtual machines has the same problem. I gave up
Thank you for your reply

**Comment by jim3ma** [comment]
How many files do you copy via smb ? And size ? Do  you test via scp, rsyc or ftp ?

**Comment by Aivenpeng** [comment]
All services are tested, including web service uploads

**Comment by Aivenpeng** [comment]
All files are tried, and will crash whenever the file size exceeds the memory size

**Comment by sbbbsbbb** [comment]
How to install DSM in dx4600? 
Need PVE?
Have tutorials？

**Comment by jim3ma** [comment]
> How to install DSM in dx4600? Need PVE? Have tutorials？

1. Burn TCRP, https://github.com/pocopico/tinycore-redpill
2. Enable boot from usb, follow this: https://post.smzdm.com/talk/p/avx6rzdp/
3. SSH to TCRP, follow the normal actions
4. Ensure igc driver, like: 
```
sudo bash -x ./rploader.sh ext ds920p-7.1.1-42962 add https://raw.githubusercontent.com/pocopico/rp-ext/main/igc/rpext-index.json
```

**Comment by sbbbsbbb** [comment]
> 

Good job bro

**Comment by sbbbsbbb** [comment]
i have a quetion :
the alst verison https://github.com/pocopico/tinycore-redpill   v0.9.2.9 not include the i225 driver. 
so when i start up the DX4600, not found the interface
can't ssh it,How did you complete the installation?

**Comment by jim3ma** [comment]
> i have a quetion : the alst verison https://github.com/pocopico/tinycore-redpill v0.9.2.9 not include the i225 driver. so when i start up the DX4600, not found the interface can't ssh it,How did you complete the installation?

Before build, add igc driver
```
sudo bash -x ./rploader.sh ext ds920p-7.1.1-42962 add https://raw.githubusercontent.com/pocopico/rp-ext/main/igc/rpext-index.json
```

**Comment by chanssl** [comment]
@Aivenpeng I copied a 20GB file from NAS to PC，The speed is 110MB/s, and all is okay.
DSM Version: ds920p-7.1.1-42962
igc drive version: 1.2.0
RAM: 16G (2% used)

@jim3ma By the way, how can I update the igc drive?

**Comment by chanssl** [comment]
> i have a quetion : the alst verison https://github.com/pocopico/tinycore-redpill v0.9.2.9 not include the i225 driver. so when i start up the DX4600, not found the interface can't ssh it,How did you complete the installation?

Burn the image and boot form USB drive, you can check the IP form Router, the host name is "box" . 
the IP same as DX4600's UGOS.

**Comment by sbbbsbbb** [comment]
> > i have a quetion : the alst verison https://github.com/pocopico/tinycore-redpill v0.9.2.9 not include the i225 driver. so when i start up the DX4600, not found the interface can't ssh it,How did you complete the installation?
> 
> Burn the image and boot form USB drive, you can check the IP form Router, the host name is "box" .

The problem has been solved

**Comment by jim3ma** [comment]
> @Aivenpeng I copied a 20GB file from NAS to PC，The speed is 110MB/s, and all is okay. DSM Version: ds920p-7.1.1-42962 igc drive version: 1.2.0 RAM: 16G (2% used)
> 
> @jim3ma By the way, how can I update the igc drive?

FYI
https://xpenology.com/forum/topic/65377-intel-i225i226-igc-driver-development-thread/?do=findComment&comment=359373

**Comment by chanssl** [comment]
> > @Aivenpeng I copied a 20GB file from NAS to PC，The speed is 110MB/s, and all is okay. DSM Version: ds920p-7.1.1-42962 igc drive version: 1.2.0 RAM: 16G (2% used)
> > @jim3ma By the way, how can I update the igc drive?
> 
> FYI https://xpenology.com/forum/topic/65377-intel-i225i226-igc-driver-development-thread/?do=findComment&comment=359373

Looks like I need to know how to startup TCRP without using HDMI, thx.

**Comment by sbbbsbbb** [comment]
> > > @Aivenpeng I copied a 20GB file from NAS to PC，The speed is 110MB/s, and all is okay. DSM Version: ds920p-7.1.1-42962 igc drive version: 1.2.0 RAM: 16G (2% used)
> > > @jim3ma By the way, how can I update the igc drive?
> > 
> > 
> > FYI https://xpenology.com/forum/topic/65377-intel-i225i226-igc-driver-development-thread/?do=findComment&comment=359373
> 
> Looks like I need to know how to startup TCRP without using HDMI, thx.

https://post.smzdm.com/talk/p/avx6rzdp/

**Comment by chanssl** [comment]
> > > > @Aivenpeng I copied a 20GB file from NAS to PC，The speed is 110MB/s, and all is okay. DSM Version: ds920p-7.1.1-42962 igc drive version: 1.2.0 RAM: 16G (2% used)
> > > > @jim3ma By the way, how can I update the igc drive?
> > > 
> > > 
> > > FYI https://xpenology.com/forum/topic/65377-intel-i225i226-igc-driver-development-thread/?do=findComment&comment=359373
> > 
> > 
> > Looks like I need to know how to startup TCRP without using HDMI, thx.
> 
> https://post.smzdm.com/talk/p/avx6rzdp/

Thank you, I mean Swith the boot options to “TCRP Builder”, and I knew it.

**Comment by Aivenpeng** [comment]
@chanssl Please try to copy the file from the computer to the NAS

**Comment by jim3ma** [comment]
@Aivenpeng Which nic do you use ? Like i225 v3 ?

**Comment by Aivenpeng** [comment]
> @Aivenpeng Which nic do you use ? Like i225 v3 ?

![image](https://user-images.githubusercontent.com/38059391/200262039-ccb77651-8cd7-43a6-85b8-eb75b68b7fe0.png)
Yes, these are my network card parameters

**Comment by chanssl** [comment]
> @chanssl Please try to copy the file from the computer to the NAS
I try to copied the file to the NAS form PC via SMB, nothing has been happened. 

![18](https://user-images.githubusercontent.com/4261299/200311368-7ddb7a5b-ef51-4486-8ca1-5e3b3b2e3ab1.png)

**Comment by chanssl** [comment]
> @chanssl Please try to copy the file from the computer to the NAS

@Aivenpeng I try to copied the file to the NAS form PC via SMB, nothing has been happened.

![18](https://user-images.githubusercontent.com/4261299/200312702-d33c0411-b496-4a9a-8c30-b08343c22bda.png)

![Snipaste_2022-11-07_20-43-21](https://user-images.githubusercontent.com/4261299/200313426-b6efb3fe-40a1-4c4f-8225-48429402c65f.png)

**Comment by Aivenpeng** [comment]
> > @chanssl请尝试将文件从计算机复制到 NAS
> 
> @Aivenpeng我尝试通过 SMB 将文件从 PC 复制到 NAS，没有任何反应。
> 
> ![18](https://user-images.githubusercontent.com/4261299/200312702-d33c0411-b496-4a9a-8c30-b08343c22bda.png)
> 
> ![Snipaste_2022-11-07_20-43-21](https://user-images.githubusercontent.com/4261299/200313426-b6efb3fe-40a1-4c4f-8225-48429402c65f.png)

What is the network port rate of your computer? 1G or 2.5G?

**Comment by chanssl** [comment]
@Aivenpeng 1000M.

**Comment by Aivenpeng** [comment]
> @Aivenpeng 1000M.

The 2.5G network interface used for my test

**Comment by Aivenpeng** [comment]
@jim3ma I found this problem only when the NIC connection speed was 2.5G. When I used a 1G connection speed, there was no memory overflow and it worked perfectly
![i225_1G_1](https://user-images.githubusercontent.com/38059391/201119517-8db336d6-ae85-4f2f-95fa-8ea29b70d779.PNG)

**Comment by Shimon-Guo** [comment]
I also met this problem when I trans 100GB file to my NAS(J4125, 16G RAM, bare install, not virtual env)
<img width="804" alt="image" src="https://user-images.githubusercontent.com/33592567/201477090-97dbd077-33b5-42fc-b28c-a526f9ede126.png">

**Comment by Shimon-Guo** [comment]
> I also met this problem when I trans 100GB file to my NAS(J4125, 16G RAM, bare install, not virtual env) <img alt="image" width="804" src="https://user-images.githubusercontent.com/33592567/201477090-97dbd077-33b5-42fc-b28c-a526f9ede126.png">

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/33592567/201479285-adaee12d-6551-459d-99de-b16f40452079.png">

**Comment by jim3ma** [comment]
Maybe same bug: https://github.com/fbelavenuto/arpl-modules/issues/59

**Comment by jim3ma** [comment]
> I also met this problem when I trans 100GB file to my NAS(J4125, 16G RAM, bare install, not virtual env) <img alt="image" width="804" src="https://user-images.githubusercontent.com/33592567/201477090-97dbd077-33b5-42fc-b28c-a526f9ede126.png">

Can you provide a dsm in virtual machine with a virtual nic and a passthrough i225 nic ? I can ssh into the vm to debug it.

**Comment by Shimon-Guo** [comment]
> 

I can provide the ssh address to you for debug it, and how can I send the information to you.

**Comment by jim3ma** [comment]
> > 
> 
> I can provide the ssh address to you for debug it, and how can I send the information to you.

I can reproduce this bug, please wait the fix.

**Comment by jim3ma** [comment]
@chanssl @yanshibin @Shimon-Guo @Aivenpeng 
Try latest version: https://github.com/jim3ma/synology-igc/releases/tag/1.3.0
The version fixes memory leak in all versions, please update to this version ASAP.

**Comment by Shimon-Guo** [comment]
> @chanssl @yanshibin @Shimon-Guo @Aivenpeng Try latest version: https://github.com/jim3ma/synology-igc/releases/tag/1.3.0 The version fixes memory leak in all versions, please update to this version ASAP.

great, I will try it later

**Comment by Aivenpeng** [comment]
> @chanssl @yanshibin @Shimon-Guo @Aivenpeng Try latest version: https://github.com/jim3ma/synology-igc/releases/tag/1.3.0 The version fixes memory leak in all versions, please update to this version ASAP.

Great. I'll update it later

**Comment by Shimon-Guo** [comment]
> @chanssl @yanshibin @Shimon-Guo @Aivenpeng Try latest version: https://github.com/jim3ma/synology-igc/releases/tag/1.3.0 The version fixes memory leak in all versions, please update to this version ASAP.

I updated the driver and found no memory leaks

**Comment by vysecurity** [comment]
I am trying to install on DX4600, but the TCRP keeps sending back to the Install PAT file page after it reboots?
