### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by tyfzpb** [jim3ma/synology-igc#4]
hi，Build is Error。

ake: Entering directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'
  CC [M]  /usr/src/synology-igc/igc_ptp.o
In file included from /usr/src/synology-igc/igc_hw.h:11:0,
                 from /usr/src/synology-igc/igc.h:17,
                 from /usr/src/synology-igc/igc_ptp.c:4:
/usr/src/synology-igc/igc_ptp.c: In function 'igc_ptm_stop':
/usr/src/synology-igc/igc_ptp.c:570:14: error: 'IGC_PTM_CTRL' undeclared (first use in this function)
  ctrl = rd32(IGC_PTM_CTRL);
              ^
/usr/src/synology-igc/igc_regs.h:260:33: note: in definition of macro 'rd32'
 #define rd32(reg) (igc_rd32(hw, reg))
                                 ^
/usr/src/synology-igc/igc_ptp.c:570:14: note: each undeclared identifier is reported only once for each function it appears in
  ctrl = rd32(IGC_PTM_CTRL);
              ^
/usr/src/synology-igc/igc_regs.h:260:33: note: in definition of macro 'rd32'
 #define rd32(reg) (igc_rd32(hw, reg))
                                 ^
/usr/src/synology-igc/igc_ptp.c:571:11: error: 'IGC_PTM_CTRL_EN' undeclared (first use in this function)
  ctrl &= ~IGC_PTM_CTRL_EN;
           ^
/usr/src/synology-igc/igc_ptp.c: At top level:
/usr/src/synology-igc/igc_ptp.c:67:12: warning: 'igc_ptp_adjfine_i225' defined but not used [-Wunused-function]
 static int igc_ptp_adjfine_i225(struct ptp_clock_info *ptp, long scaled_ppm)
            ^
scripts/Makefile.build:277: recipe for target '/usr/src/synology-igc/igc_ptp.o' failed
make[1]: *** [/usr/src/synology-igc/igc_ptp.o] Error 1
Makefile:1449: recipe for target '_module_/usr/src/synology-igc' failed
make: *** [_module_/usr/src/synology-igc] Error 2
make: Leaving directory '/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-7.1/build'

**Comment by jim3ma** [comment]
You can build with docker container from arpl repo: https://github.com/fbelavenuto/arpl-modules/blob/main/src/.compile.sh

I will update README.md later.

**Comment by jim3ma** [comment]
I have update the source code and test building, it works now.
