### ISSUE TITLE
Help to build driver for EGPL-T101 M.2 based 10Gbit NIC. 

### ISSUE THREAD

**Issue by cvondra** [jim3ma/synology-igc#9]
I was wondering if you could help me.  I have a 1520+ (geminilake) and I purchased a EGPL-T101.  On the Innodisk website is the linux driver source (at the bottom of the page).  I am not very well versed in linux and was wondering if you could help me build this driver.  Thanks for any help you may provide!

https://www.innodisk.com/en/products/embedded-peripheral/communication/egpl-t101

Chad

**Comment by wjz304** [comment]
Hi, bro
https://raw.githubusercontent.com/pocopico/rp-ext/main/atlantic/rpext-index.json
Have you tried ?

**Comment by cvondra** [comment]
How would I install that?

**Comment by wjz304** [comment]
https://raw.githubusercontent.com/pocopico/rp-ext/master/atlantic/releases/atlantic-4.4.180plus-geminilake.tgz  
From this link, you can get the driver file of ".ko".
Refer to the loading method of igc in the [README.md](https://github.com/jim3ma/synology-igc#readme) for installation.

![image](https://user-images.githubusercontent.com/5615843/205212103-76d53062-7425-454b-83e6-33416bc49262.png)

**Comment by cvondra** [comment]
SFP+ in switch is a 10Gbit.  The Innodisk M.2 is showing a 5Gbit connection in DSM.  The SFP+ is showing a 10Gbit connection in Ubiquiti console.  Is that driver for a 5Gbit card?

<img width="1102" alt="NASNIC" src="https://user-images.githubusercontent.com/24215922/205415738-f5af9b1c-efa2-47a5-8c8c-751c35fdb8e4.png">
<img width="1155" alt="SwitchSFP10Gbit" src="https://user-images.githubusercontent.com/24215922/205415759-b785bb27-955f-418e-b0cf-07a5881f3afc.png">

**Comment by wjz304** [comment]
I'm sorry, I don't have this equipment, so I don't know the details,
It may be a compatibility problem caused by an older driver (I'm just guessing).
Because pocopico is maintaining it, and there are many people using the [pocopico](https://github.com/pocopico/rp-ext) library, if pocopico fix it, will help more people, so I think you can give him a feedback.

**Comment by wjz304** [comment]
I am sorry for my broken English.

**Comment by cvondra** [comment]
Crazy enough swapped cable and everything is running at 10Gbit now.  Thanks for your help!

**Comment by wjz304** [comment]
happy for you.
